# 2. 넘파이로 텐서 만들기(벡터와 행렬 만들기)

In [1]:
import numpy as np

## 1) 1D with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ',t.ndim) # 몇 차원인지 출력
print('Shape of t:', t.shape)

Rank of t:  1
Shape of t: (7,)


### 1-1) Numpy 기초 이해하기

In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])  # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [5]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # 시작번호: 끝번호로 범위 지정을 통해 가져온다.

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [6]:
print('t[:2] t[3:]', t[:2], t[3:])  # 시작번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:] [0. 1.] [3. 4. 5. 6.]


## 2) 2D with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


# 3. 파이토치 텐서 선언하기(Pytorch Tensor Allocation)

In [9]:
import torch

## 1) 1D with Pytorch

In [10]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [12]:
print(t[0], t[1], t[-1])    # 인덱스로 접근
print(t[2:5], t[4:-1])  # 슬라이싱
print(t[:2], t[3:]) # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2) 2D with Pytorch

In [13]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [15]:
print(t[:, 1])  # 첫번째 차원을 전체 선택한 상황에서 두 번째 차원의 첫번째 것만 가져온다.
print(t[:,1].size())    # 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [16]:
print(t[:, :-1])    # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## 3) 브로드 캐스팅(Broadcasting)

In [17]:
# 같은 크기일때 연산을 하는 경우
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [19]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3,3]
print(m1 + m2)

tensor([[4., 5.]])


In [20]:
# 1 x 2 Vector + 2 x 1 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 4) 자주 사용되는 기능들

## 1) 행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)

In [21]:
# 행렬 곱셈
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of matrix 1:', m1.shape)    # 2x2
print('Shape of matrix 2:', m2.shape)   # 2x1
print(m1.matmul(m2))    # 2 x 1

Shape of matrix 1: torch.Size([2, 2])
Shape of matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [23]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of matrix 1:', m1.shape)   # 2 x 2
print('Shape of matrix 2:', m2.shape)   # 2 x 1
print(m1 * m2)
print(m1.mul(m2))

Shape of matrix 1: torch.Size([2, 2])
Shape of matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 2) 평균(Mean)

In [24]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [25]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
print(t.mean())

tensor(2.5000)


In [27]:
print(t.mean(dim=0))    # 인자로 dim을 주면 해당 차원을 제거한다는 의미. -> 즉, 최종 결과에서는 행을 제거하므로 '열'만 남김 -> 열방향

tensor([2., 3.])


In [29]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [30]:
print(t.mean(dim=-1))   # 인자로 -1을 주면 마지막 차원을 제거하겠다는 의미

tensor([1.5000, 3.5000])


## 3) 덧셈(Sum)

In [31]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [32]:
print(t.sum())  # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1))    # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [33]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
print(t.max())  # returns one value: max

tensor(4.)


In [35]:
print(t.max(dim=0)) # returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [36]:
print('Max: ',t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [37]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경

In [38]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [40]:
print(ft.shape) # 첫번째 중괄호의 원소 개수, 두번째 중괄호의 원소 개수, 3번째 중괄호의 원소 개수

torch.Size([2, 2, 3])


## 5-1) 3차원 텐서에서 2차원 텐서로 변경

In [42]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [46]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## 6) 스퀴즈(Squeeze) - 1인 차원을 제거한다

In [47]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [48]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [49]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [50]:
print(ft.unsqueeze(0))  # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


## 7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [51]:
# view를 통한 구현
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [52]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [53]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## 8) 타입 캐스팅(Type Casting)

In [54]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [55]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [56]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [57]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## 9) 연결하기(concatenate)

In [58]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [59]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [60]:
print(torch.cat([x, y],dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## 10) 스택킹(Stacking)

In [61]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [62]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [63]:
print(torch.stack([x,y,z],dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 11) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [64]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [65]:
print(torch.ones_like(x))   # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [66]:
print(torch.zeros_like(x))  # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 12) In-place Operation(덮어쓰기 연산)

In [67]:
x = torch.FloatTensor([[1,2],[3,4]])

In [68]:
print(x.mul(2)) # 곱하기 2를 수행한 결과를 출력
print(x)    # 기존 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [69]:
print(x.mul_(2.))   # 곱하기 2를 수행한 결과를 변수 x에 저장하면서 결과를 출력
print(x)    # 기존 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# 02-03 파이썬 클래스(class)

## 1. 함수(function)와 클래스(Class)의 차이

### 1. 함수(function)로 덧셈기 구현하기

In [70]:
result = 0  # 전역변수

In [71]:
def add(num):
    global result
    result += num
    return result

In [72]:
print(add(3))
print(add(4))

3
7


### 2. 함수(function)로 두 개의 덧셈기 구현하기

In [73]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


## 3. 클래스(class)로 덧셈기 구현하기

In [74]:
class Calculator:
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 초기화 함수. 이를 생성자라고 한다.
        self.result = 0

    def add(self, num): # 객체 생성 후 사용할 수 있는 함수
        self.result += num
        return self.result

In [75]:
cal1 = Calculator()

In [76]:
cal2 = Calculator()

In [77]:
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
