<a href="https://colab.research.google.com/github/gagyeomkim/pytorch-deep-learning-Intro/blob/main/03_%5BML_%EC%9E%85%EB%AC%B8%5D_%E2%80%91_%EB%A8%B8%EC%8B%A0_%EB%9F%AC%EB%8B%9D_%EC%9E%85%EB%AC%B8%ED%95%98%EA%B8%B0_(Machine_Learning_Basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03‑01 선형 회귀와 자동 미분(Linear Regression and Autograd)

## 1. 데이터에 대한 이해(Data Definition)

In [ ]:
import torch

In [ ]:
# 훈련 데이터 셋의 구성
x_train = torch.FloatTensor([[1],[2],[3]])  # 공부한 시간
y_train = torch.FloatTensor([[2],[4],[6]])  # 그에 맵핑되는 점수

## 5. 파이토치로 선형회귀 구현하기

***기본 셋팅***

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
torch.manual_seed(1)

***변수선언***

In [ ]:
# 훈련 데이터 셋의 구성
x_train = torch.FloatTensor([[1],[2],[3]])  # 공부한 시간
y_train = torch.FloatTensor([[2],[4],[6]])  # 그에 맵핑되는 점수

In [ ]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


***가중치와 편향의 초기화***

In [ ]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [ ]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


***가설 세우기***

In [ ]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


***비용 함수 선언하기***

In [ ]:
# 앞서 배운 torch.mean으로 평균을 구한다.
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


***경사하강법 구현하기***

In [ ]:
optimizer = optim.SGD([W,b], lr=0.01)

In [ ]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

***전체 코드***

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W,b], lr = 0.01)

nb_epochs = 2000    # 원하는 만큼 경사하강법을 반복
for epoch in range(nb_epochs+1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train)**2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b:{:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.187, b:0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b:0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b:0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b:0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b:0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b:0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b:0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b:0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b:0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b:0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b:0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b:0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b:0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b:0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b:0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b:0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b:0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b:0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b:0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b:0.008 Cost: 0.000008
Epoch 2000/2000 W: 

## 6. optimizer.zero_grad()가 필요한 이유

In [ ]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    z = 2 * w
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


## 7. torch.manual_seed()를 하는 이유

In [ ]:
import torch

In [ ]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [ ]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [ ]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


## 8. 자동 미분(Autograd) 실습하기

$$2w^2 + 5$$

In [ ]:
import torch

In [ ]:
w = torch.tensor(2.0, requires_grad=True)   # 이 텐서에 대한 기울기를 저장하겠다

In [ ]:
y = w ** 2
z = 2 * y + 5   # cost

In [ ]:
z.backward()

In [ ]:
print('수식을 w로 미분한 값: {}'.format(w.grad))

수식을 w로 미분한 값: 8.0


# 03-02 다중 선형 회귀(Multivariable Linear regression)

## 2. 파이토치로 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
# 훈련 데이터
x1_train = torch.FloatTensor([[73],[93],[89],[96], [73]])
x2_train = torch.FloatTensor([[80],[88],[91],[98], [66]])
x3_train = torch.FloatTensor([[75],[93],[80],[100], [70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [ ]:
# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs=1000
for epoch in range(nb_epochs+1):
    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train*w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train)**2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번 마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d} / {} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0 / 1000 w1: 0.461 w2: 0.460 w3: 0.455 b: 0.005 Cost: 9537.694336
Epoch  100 / 1000 w1: 0.688 w2: 0.681 w3: 0.658 b: 0.008 Cost: 5.752121
Epoch  200 / 1000 w1: 0.698 w2: 0.684 w3: 0.645 b: 0.008 Cost: 5.510032
Epoch  300 / 1000 w1: 0.707 w2: 0.686 w3: 0.634 b: 0.008 Cost: 5.279399
Epoch  400 / 1000 w1: 0.716 w2: 0.689 w3: 0.622 b: 0.008 Cost: 5.059760
Epoch  500 / 1000 w1: 0.724 w2: 0.691 w3: 0.611 b: 0.008 Cost: 4.850370
Epoch  600 / 1000 w1: 0.733 w2: 0.693 w3: 0.600 b: 0.008 Cost: 4.650773
Epoch  700 / 1000 w1: 0.742 w2: 0.695 w3: 0.589 b: 0.009 Cost: 4.460444
Epoch  800 / 1000 w1: 0.750 w2: 0.697 w3: 0.579 b: 0.009 Cost: 4.278834
Epoch  900 / 1000 w1: 0.758 w2: 0.699 w3: 0.569 b: 0.009 Cost: 4.105582
Epoch 1000 / 1000 w1: 0.766 w2: 0.700 w3: 0.559 b: 0.009 Cost: 3.940238


## 4. 행렬 연산을 고려하여 파이토치로 구현하기

In [ ]:
# 훈련 데이터 선언
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152],[184],[180],[196],[142]])

In [ ]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [ ]:
# 가중치와 편향 선언
W = torch.zeros((3,1),requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
hypothesis = x_train.matmul(W) + b  # 그냥 *을 쓰면 요소별 곱셈

***전체코드***

In [ ]:
# 훈련 데이터 선언
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152],[184],[180],[196],[142]])

# 모델 초기화
W = torch.zeros((3,1),requires_grad=True)
b = torch.zeros(1, requires_grad=True)
#optimizer 설정
optimizer = optim.SGD([W,b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train)**2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epcoh {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epcoh    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29588.000000
Epcoh    1/20 hypothesis: tensor([66.6346, 80.0699, 76.0076, 85.9120, 61.0801]) Cost: 9514.111328
Epcoh    2/20 hypothesis: tensor([104.4118, 125.4639, 119.0992, 134.6178,  95.7082]) Cost: 3062.145996
Epcoh    3/20 hypothesis: tensor([125.8288, 151.1989, 143.5296, 162.2304, 115.3400]) Cost: 988.415222
Epcoh    4/20 hypothesis: tensor([137.9707, 165.7888, 157.3805, 177.8846, 126.4698]) Cost: 321.893463
Epcoh    5/20 hypothesis: tensor([144.8543, 174.0600, 165.2335, 186.7592, 132.7797]) Cost: 107.664345
Epcoh    6/20 hypothesis: tensor([148.7568, 178.7491, 169.6861, 191.7902, 136.3569]) Cost: 38.806896
Epcoh    7/20 hypothesis: tensor([150.9692, 181.4073, 172.2109, 194.6422, 138.3849]) Cost: 16.673267
Epcoh    8/20 hypothesis: tensor([152.2234, 182.9142, 173.6428, 196.2588, 139.5347]) Cost: 9.557421
Epcoh    9/20 hypothesis: tensor([152.9345, 183.7683, 174.4551, 197.1750, 140.1865]) Cost: 7.268370
Epcoh   10/20 hyp

In [ ]:
# 임의의 입력 값에 대한 예측
with torch.no_grad():
    new_input = torch.FloatTensor([[75, 85, 72]])   # 예측하고 싶은 임의의 입력
    prediction = new_input.matmul(W) + b    # 학습이 완료된 후, W와 b를 이용한 예측
    print('Predicted value for input {}: {}'.format(new_input.squeeze().tolist(), prediction.item()))

Predicted value for input [75.0, 85.0, 72.0]: 156.61285400390625


# 03-03 nn.Module과 클래스로 구현하기

## 1. 단순 선형 회귀 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
# 모델을 선언및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1
model = nn.Linear(1, 1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
# optimizer 설정. 경사하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
# 전체 훈련 데이터에 대해 경사하강법을 2000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)  # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴 받아서 pred_y에 저장
pred_y = model(new_var)
# y = 2x이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print('훈련 후 입력이 4일 때의 예측값 :', pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [ ]:
# 학습 후의 W와 b의 값
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## 2. 다중 선형 회귀 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [ ]:
# 모델을 선언 및 초기화. 다중 선형 회귀 이므로 input_dim = 3, output_dim = 1
model = nn.Linear(3, 1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)과 동일함

    # cost 계산
    cost = F.mse_loss(prediction, y_train)  # <== 파이토치에서 제공하는 평균 제곱 오차

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용함수를 미분하여 gradient 게산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch%100 == 0:
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [ ]:
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print('훈련후 입력이 73, 80, 75일 때의 에측값: ', pred_y)

훈련후 입력이 73, 80, 75일 때의 에측값:  tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


## 3. 모델을 클래스로 구현하기

***단순 선형 회귀***

In [ ]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1
# model = nn.Linear(1, 1)

class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)   # 단순 선형 회귀이므로 input_dim=1, output_dim=1

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = LinearRegressionModel()

***다중 선형 회귀***

In [ ]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1
# model = nn.Linear(3, 1)

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)    # 다중 선형 회귀 이므로 input_dim=3, output_dim=1

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = MultivariateLinearRegressionModel()

## 4. 단순 선형 회귀 클래스로 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = LinearRegressionModel()

In [ ]:
# optimizer 설정. 경사하강법 SGD를 사용하고 Learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)  # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch %100 == 0:
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


## 5. 다중 선형 회귀 클래스로 구현하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
#데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96 ,98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180],[196],[142]])

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)   # 다중 선형 회귀이므로 input_dim = 3, output_dim=1

    def forward(self, x):
        return self.linear(x)

model = MultivariateLinearRegressionModel()

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 개선하는 부분
    #gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost:{:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost:31667.597656
Epoch  100/2000 Cost:0.225993
Epoch  200/2000 Cost:0.223911
Epoch  300/2000 Cost:0.221941
Epoch  400/2000 Cost:0.220059
Epoch  500/2000 Cost:0.218271
Epoch  600/2000 Cost:0.216575
Epoch  700/2000 Cost:0.214950
Epoch  800/2000 Cost:0.213413
Epoch  900/2000 Cost:0.211952
Epoch 1000/2000 Cost:0.210560
Epoch 1100/2000 Cost:0.209232
Epoch 1200/2000 Cost:0.207967
Epoch 1300/2000 Cost:0.206761
Epoch 1400/2000 Cost:0.205619
Epoch 1500/2000 Cost:0.204522
Epoch 1600/2000 Cost:0.203484
Epoch 1700/2000 Cost:0.202485
Epoch 1800/2000 Cost:0.201542
Epoch 1900/2000 Cost:0.200635
Epoch 2000/2000 Cost:0.199769


# 03-04 미니 배치와 데이터 로더(Mini Batch and DataLoader)

## 3. 데이터 로드하기

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
from torch.utils.data import TensorDataset  # 텐서 데이터셋
from torch.utils.data import DataLoader # 데이터 로더

In [ ]:
#데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96 ,98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180],[196],[142]])

In [ ]:
dataset = TensorDataset(x_train, y_train)

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        # print(batch_idx)
        # print(samples)
        x_train, y_train = samples
        #H(x) 계산
        prediction = model(x_train)

        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch: {:4d}/{} Batch {}/{} cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
        ))

Epoch:    0/20 Batch 1/3 cost: 2.105971
Epoch:    0/20 Batch 2/3 cost: 0.110010
Epoch:    0/20 Batch 3/3 cost: 0.249847
Epoch:    1/20 Batch 1/3 cost: 1.496397
Epoch:    1/20 Batch 2/3 cost: 0.099472
Epoch:    1/20 Batch 3/3 cost: 1.706712
Epoch:    2/20 Batch 1/3 cost: 0.213913
Epoch:    2/20 Batch 2/3 cost: 0.372176
Epoch:    2/20 Batch 3/3 cost: 3.877178
Epoch:    3/20 Batch 1/3 cost: 1.114850
Epoch:    3/20 Batch 2/3 cost: 0.244837
Epoch:    3/20 Batch 3/3 cost: 2.249039
Epoch:    4/20 Batch 1/3 cost: 0.212871
Epoch:    4/20 Batch 2/3 cost: 2.397416
Epoch:    4/20 Batch 3/3 cost: 0.154225
Epoch:    5/20 Batch 1/3 cost: 1.274019
Epoch:    5/20 Batch 2/3 cost: 1.376830
Epoch:    5/20 Batch 3/3 cost: 0.271835
Epoch:    6/20 Batch 1/3 cost: 0.111913
Epoch:    6/20 Batch 2/3 cost: 2.014438
Epoch:    6/20 Batch 3/3 cost: 0.045024
Epoch:    7/20 Batch 1/3 cost: 0.580636
Epoch:    7/20 Batch 2/3 cost: 2.231197
Epoch:    7/20 Batch 3/3 cost: 0.096108
Epoch:    8/20 Batch 1/3 cost: 1.472891


In [ ]:
# 임의의 입력 [73, 80. 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75일때의 예측값: ', pred_y)

훈련 후 입력이 73, 80, 75일때의 예측값:  tensor([[150.3001]], grad_fn=<AddmmBackward0>)


## 5. 커스텀 데이터셋(Custom Dataset)으로 선형회귀 구현하기

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [ ]:
# Dataset 상속
class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96 ,98, 100],
                       [73, 66, 70]]
        self.y_data = [[152],[185],[180],[196],[142]]

    # 총 데이터의 개수를 리턴
    def __len__(self):
        return len(self.x_data)

    # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [ ]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
model = torch.nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        #H(x) 계산
        prediction = model(x_train)
        #cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 28286.632812
Epoch    0/20 Batch 2/3 Cost: 12009.502930
Epoch    0/20 Batch 3/3 Cost: 3635.381836
Epoch    1/20 Batch 1/3 Cost: 800.603088
Epoch    1/20 Batch 2/3 Cost: 323.736725
Epoch    1/20 Batch 3/3 Cost: 111.539330
Epoch    2/20 Batch 1/3 Cost: 29.674530
Epoch    2/20 Batch 2/3 Cost: 6.392916
Epoch    2/20 Batch 3/3 Cost: 0.403974
Epoch    3/20 Batch 1/3 Cost: 1.649625
Epoch    3/20 Batch 2/3 Cost: 0.212619
Epoch    3/20 Batch 3/3 Cost: 4.296056
Epoch    4/20 Batch 1/3 Cost: 0.147060
Epoch    4/20 Batch 2/3 Cost: 0.861325
Epoch    4/20 Batch 3/3 Cost: 2.984918
Epoch    5/20 Batch 1/3 Cost: 1.486548
Epoch    5/20 Batch 2/3 Cost: 1.312422
Epoch    5/20 Batch 3/3 Cost: 0.131674
Epoch    6/20 Batch 1/3 Cost: 0.156190
Epoch    6/20 Batch 2/3 Cost: 1.062103
Epoch    6/20 Batch 3/3 Cost: 2.878484
Epoch    7/20 Batch 1/3 Cost: 0.818869
Epoch    7/20 Batch 2/3 Cost: 0.290195
Epoch    7/20 Batch 3/3 Cost: 2.282895
Epoch    8/20 Batch 1/3 Cost: 0.226800
Epoch  

In [ ]:
# 임의의 입력 [73, 80, 75]를 선언
new_var = torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75일때의 예측값: ',pred_y)

훈련 후 입력이 73, 80, 75일때의 예측값:  tensor([[150.4151]], grad_fn=<AddmmBackward0>)


# 03-05 벡터와 행렬연산 복습하기

## 2. 텐서(Tensor)

In [ ]:
import numpy as np

### 1) 0차원 텐서(스칼라)

In [ ]:
d = np.array(5)
print('텐서의 차원',d.ndim)
print('텐서의 크기(shape)',d.shape)

텐서의 차원 0
텐서의 크기(shape) ()


### 2) 1차원 텐서(벡터)

In [ ]:
d = np.array([1, 2, 3, 4])
print('텐서의 차원 : ', d.ndim)
print('텐서의 크기(shape) : ', d.shape) # 벡터의 차원 = 4

텐서의 차원 :  1
텐서의 크기(shape) :  (4,)


###3) 2차원 텐서 (행렬)

In [ ]:
# 3행 4열의 행렬
d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print('텐서의 차원 : ',d.ndim)
print('텐서의 크기(shape) :', d.shape)

텐서의 차원 :  2
텐서의 크기(shape) : (3, 4)


In [ ]:
d = np.array([
    [[1,2,3,4,5], [6,7,8,9,10],[10, 11,12,13,14]],
    [[15,16,17,18,19],[19,20,21,22,23],[23,24,25,26,27]]
])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape): ', d.shape)

텐서의 차원 : 3
텐서의 크기(shape):  (2, 3, 5)


## 3. 벡터와 행렬의 연산

In [ ]:
import numpy as np

### 1) 벡터와 행렬의 덧셈과 뺄셈

In [ ]:
A = np.array([8, 4, 5])
B = np.array([1, 2, 3])
print('두 벡터의 합:',A+B)
print('두 벡터의 차:',A-B)

두 벡터의 합: [9 6 8]
두 벡터의 차: [7 2 2]


In [ ]:
A = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print('두 행렬의 합 :')
print(A+B)
print('두 행렬의 차 :')
print(A-B)

두 행렬의 합 :
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 :
[[ 5 14 23 32]
 [49 58 67 76]]


### 2) 벡터의 내적과 행렬의 곱셈

In [ ]:
A = np.array([1,2,3])
B = np.array([4, 5, 6])
print('두 벡터의 내적 : ', np.dot(A,B))

두 벡터의 내적 :  32


In [ ]:
A = np.array([[1, 3], [2, 4]])
B = np.array([[5, 7], [6, 8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A,B))

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]
